version: '3.8'
services:
  db:
    image: mysql:latest
    volumes: 
      - /db:/var/lib/mysql
    container_name: grpc-api-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "*P*ndor*2018*"
      MYSQL_DATABASE: grpc_api_db
    ports:
      - "3306:3306"
  api:
    build: # User the Dockerfile from the current directory to build container
      context: . 
    container_name: grpc-api
    # image: grpc-api-service:latest
    # restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_USER=root 
      - DB_PASS=*P*ndor*2018*
      - CONN_TYPE=tcp
      - HOST_NAME=db:3306
      - DB_NAME=grpc_api_db
    depends_on:
      - "db"   